import { Bathroom } from "./types";

export const bathrooms: Bathroom[] = [
  {
    id: "1",
    name: "Jardim Central WC",
    latitude: 38.793,
    longitude: -9.183,
    address: "Odivelas, Lisboa",
    place_description: "Near the main garden entrance",
    free_or_paid: "free",
    price_if_known: null,
    opening_hours: "08:00-20:00",
    wheelchair_accessible: true,
    step_free_access: true,
    baby_changing: false,
    gender_neutral: false,
    family_friendly: true,
    requires_code: false,
    code_hint: null,
    status: "open",
    cleanliness_avg: 4.1,
    safety_avg: 4.0,
    accessibility_avg: 4.3,
    trust_score: 82,
    number_of_confirmations: 9,
    report_count: 1,
    last_verified_at: "2026-04-20T10:30:00Z",
  },
  {
    id: "2",
    name: "Metro Station Restroom",
    latitude: 38.794,
    longitude: -9.179,
    address: "Inside station concourse",
    place_description: "After ticket gates",
    free_or_paid: "paid",
    price_if_known: "0.50 EUR",
    opening_hours: "06:00-23:00",
    wheelchair_accessible: true,
    step_free_access: true,
    baby_changing: true,
    gender_neutral: false,
    family_friendly: true,
    requires_code: false,
    code_hint: null,
    status: "open",
    cleanliness_avg: 3.7,
    safety_avg: 4.2,
    accessibility_avg: 4.0,
    trust_score: 76,
    number_of_confirmations: 14,
    report_count: 2,
    last_verified_at: "2026-04-26T08:15:00Z",
  },
];